
path: '/content/drive/MyDrive/custom_dataset_yolov5_new/data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')
nc: 1
# Classes
names:
  0: car
